### PR TITLE
Create react-native project

### LINKED ISSUE #2: Set up react native/package.json
Set up basic npm dependencies, including react native

### PR DESCRIPTION
**Pull request by adanoff**
Closes #2. 

Created the react-native project for the bitcamp app. It can be run with
`react-native run-ios` and `react-native run-android` respectively.

### CODE REVIEW

**Comment by jdai8** [comment]
Is is standard to create our React-Native project in a subfolder (`BitcampApp`)? 
Wouldn't it be nicer to just have our `package.json`, etc in the root?

**Comment by adanoff** [comment]
`react-native init` created the `BitcampApp` folder. We could potentially take everything out and put it into the root, but if we wanna have other things (e.g. backend or designs) in the repo then we wanna have separate folders for that anyway. In my opinion, that other stuff shouldn't live in `BitcampApp` but if you disagree I'm open to discussing it

**Comment by jdai8** [comment]
Yeah I agree the backend and design stuff should be separate from the mobile app.  We could also make separate repos for each part (mobile app, backend, design, whatever), but it might be harder to track issues if they're spread across multiple repos. I don't really have a preference either way. 

Does anyone else have a preference or wants to set up another way? If not, we can just merge this the way it is.

**Comment by jsjqian** [comment]
I think the way Alex currently has it setup will work for us because we can keep all of the designs for the mobile app in the same repo so it'll be easy to access. We will be making separate repos for the backend and all of the other stuff mentioned in the Slack post George made. It LGTM so if we could get a couple more people to give a "ship it" I'll merge the pull request.

**Comment by AyeAndy** [comment]
LGTM. Let's go team! :)

**Comment by jsjqian** [comment]
Actually, after further consideration, we should avoid having a BitcampApp folder within the bitcamp-app directory. It just makes more sense to have everything clear right away instead of having another hoop to jump through. Alex, I don't know if you want to make those changes but I can try to go in and do that if you are busy with other things. Please respond asap, thanks.

**Pull request closed without merging**
